# Generated by Django 2.1 on 2018-08-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
    ]
